### ISSUE TITLE
Commented out line we probably dont need

### ISSUE THREAD

**Issue by castaway** [Siemplexus/DBIx-Class-Storage-DBI-MariaDB#1]
https://github.com/Siemplexus/DBIx-Class-Storage-DBI-MariaDB/blob/f523c0623b75cc96a1533ef724971caa44c5254a/lib/DBIx/Class/Storage/DBI/MariaDB.pm#L42

**Comment by antoniskalou** [comment]
fixed in https://github.com/Siemplexus/DBIx-Class-Storage-DBI-MariaDB/commit/250c842c46cc806c0cd80cd114adaaf048e6311b
