### ISSUE TITLE
There isnt a SQL::Translator Producer that sends mariadb_version

### ISSUE THREAD

**Issue by castaway** [Siemplexus/DBIx-Class-Storage-DBI-MariaDB#2]
https://github.com/Siemplexus/DBIx-Class-Storage-DBI-MariaDB/blob/f523c0623b75cc96a1533ef724971caa44c5254a/lib/DBIx/Class/Storage/DBI/MariaDB.pm#L138

See - https://metacpan.org/release/VEESH/SQL-Translator-1.63/source/lib/SQL/Translator/Producer/MySQL.pm .. should probably a) test this b) figure out how it would be supported / integrate ?

**Comment by fleetfootmike** [comment]
Bit of a can of worms here, since we should probably look at creating a module for `SQL/Translator/**/MariaDB.pm`? there are places in the MySQL versions of those with calls to `parse_mysql_version` that ought to handle MariaDB versions instead.

**Comment by antoniskalou** [comment]
Added tests (https://github.com/Siemplexus/DBIx-Class-Storage-DBI-MariaDB/commit/f7dc542fec13f6f119464700ba90e3b374353941) for the MySQL translator, seems to work fine.

SQL::Translator::Producer::MySQL uses >= for versions, so even if the version is 10.x it shouldn't be a problem. See [this](https://metacpan.org/release/VEESH/SQL-Translator-1.63/source/lib/SQL/Translator/Producer/MySQL.pm#L305).
